### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by ricsv**
Use Docusaurus over Jekyll Pages for documentation purposes. Previous documentation have been moved over to a new structure and a page to browse the specification is now autogenerated. This eliminates the need for double maintenance where parameters and responses had to be manually updated on markdown pages after making changes to the specification.

GitHub Pages is still used for deployment and you can see the new documentation already on: https://sambruk.github.io/Open-Meal/. A few guides are missing and will be added at a later point. Some graphical work is also needed for logotype and images linking to guides from the intro page.

Together with this, a number of GitHub Actions have been added:

- deploy -> deploys the documentation automatically to the `gh-pages` branch after making changes on `main`
- test-deploy -> builds the documentation and makes sure there are no errors before merging to main
- validate-spec -> validates the OpenAPI specification and makes sure there are no errors before merging to main

Additionally, the following changes were made to the specification:

- Conversion to `yml` for increased readability
- Added descriptions for most parameters and properties in responses 
- Added a few example responses

### CODE REVIEW

**Review by wincentek — APPROVED** [review]
Do it :)
An Icon is currently beeing worked on.

**Comment by ricsv** [comment]
> Do it :) An Icon is currently beeing worked on.

I've added the icon and updated the theme colors to match - result will be viewable after merge!

**Comment by Lonestarrk** [comment]
Why change to YAML.. way easier to make in invalid indentation then to use braces… 
Readability as an argument is to me a bit strange when the specification file is not ment to be read, the docs are

**Comment by wincentek** [comment]
> Why change to YAML.. way easier to make in invalid indentation then to use braces… Readability as an argument is to me a bit strange when the specification file is not ment to be read, the docs are

Personally I prefer yaml since I like to easily understand the data when I read it with my human eyes. Absolutely; In the end the data is not intended to be read by a human, but it's us that manage, update and make changes to the document. To me there's no reason in itself to make it harder to read when there's no specific need for JSON.

I won't fight to make it yaml or json though, just weighing in my opinion.

**Pull request merged**
